### ISSUE TITLE
On error with parsing, would be helpful to know location

### ISSUE THREAD

**Issue by devbeard** [ecoAPM/dotnet-libyear#25]
**Observation:**

- Dependencies with issues like version parsing failure, will cause an exception to be dumped to stdout. See example 1 below.
- There is no way of knowing the context if there are many project files in subdirectories

**Thought:**

- Implement a fix so that printing an exception also prints "context". Which project file was being parsed? Which package failed parsing?

**Example 1:**

```
Sorry, an unexpected exception has occurred: System.ArgumentException: '1.0' is not a valid version string. (Parameter 'value')
   at NuGet.Versioning.SemanticVersion.Parse(String value)
   at LibYear.Lib.FileTypes.XmlProjectFile.<>c__DisplayClass10_0.<.ctor>b__1(XElement d) in X:\LibYear\src\LibYear.Lib\FileTypes\XmlProjectFile.cs:line 31
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at LibYear.Lib.FileTypes.XmlProjectFile..ctor(String filename, String elementName, String[] packageAttributeNames, String versionAttributeName) in X:\LibYear\src\LibYear.Lib\FileTypes\XmlProjectFile.cs:line 29
```

**Comment by SteveDesmond-ca** [comment]
Fixed in v6.0.0
